// Каталог каноничных звериных форм друида по правилам D&D 5e.
// Содержит боевые характеристики, атаки, скорость и особые черты каждого зверя.

import type { Attack, CombatAbility } from "./types";

export interface BeastForm {
  id: string;
  name: string;
  nameEn: string;
  cr: number; // Опасность (0, 0.25, 0.5, 1, 2, 3, 5)
  size: "tiny" | "small" | "medium" | "large" | "huge";
  type: "beast" | "elemental";
  minLevel: number; // Минимальный уровень друида (базовый)
  moonDruidOnly?: boolean; // Доступно раньше только Кругу Луны
  moonDruidMinLevel?: number; // Минимальный уровень для Круга Луны
  swim?: boolean; // Требует 4+ ур (или 2 для Луны)
  fly?: boolean; // Требует 8+ ур
  ac: number;
  hpMax: number;
  speed: number;
  climb?: number;
  swimSpeed?: number;
  flySpeed?: number;
  burrowSpeed?: number;
  abilityMods: {
    STR: number;
    DEX: number;
    CON: number;
  };
  attacks: Attack[];
  abilities: CombatAbility[];
  traits: string[]; // Описание пассивных черт (напр. "Стайная тактика", "Острый нюх")
  description: string;
  icon: string; // Emoji или иконка
}

export const BEAST_FORMS: BeastForm[] = [
  // ================= CR 0 - 1/4 (Доступны с 2 уровня) =================
  {
    id: "wolf",
    name: "Волк",
    nameEn: "Wolf",
    cr: 0.25,
    size: "medium",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 13,
    hpMax: 11,
    speed: 40,
    abilityMods: { STR: 1, DEX: 2, CON: 1 },
    attacks: [
      {
        id: "wolf_bite",
        name: "Укус волка",
        attackBonus: 4,
        damage: [{ dice: "2d4", mod: 2, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        finesse: true,
        description: "При попадании цель совершает спасбросок СИЛ (СЛ 11) или сбивается с ног (prone).",
      },
    ],
    abilities: [],
    traits: [
      "Стайная тактика: преимущество на броски атак, если рядом с целью в 5 фт есть дееспособный союзник.",
      "Острый слух и тонкий нюх: преимущество на проверки Внимательности.",
    ],
    description: "Быстрый хищник, способный сбивать врагов с ног и терзать их в стае.",
    icon: "🐺",
  },
  {
    id: "boar",
    name: "Кабан",
    nameEn: "Boar",
    cr: 0.25,
    size: "medium",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 11,
    hpMax: 11,
    speed: 40,
    abilityMods: { STR: 1, DEX: 0, CON: 1 },
    attacks: [
      {
        id: "boar_tusk",
        name: "Бивни кабана",
        attackBonus: 3,
        damage: [{ dice: "1d6", mod: 1, type: "slashing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Удар острыми бивнями.",
      },
    ],
    abilities: [],
    traits: [
      "Таран (Charge): если кабан пробежал по прямой не менее 20 фт перед атакой, он наносит +1d6 урона и цель с СЛ 11 СИЛ сбивается с ног.",
      "Стойкость (Relentless): при получении смертельного урона один раз остаётся с 1 HP.",
    ],
    description: "Яростный вепрь с крепким телосложением и опасным тараном с разбега.",
    icon: "🐗",
  },
  {
    id: "panther",
    name: "Пантера",
    nameEn: "Panther",
    cr: 0.25,
    size: "medium",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 12,
    hpMax: 13,
    speed: 50,
    climb: 40,
    abilityMods: { STR: 2, DEX: 2, CON: 0 },
    attacks: [
      {
        id: "panther_bite",
        name: "Укус пантеры",
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        finesse: true,
      },
      {
        id: "panther_claws",
        name: "Когти пантеры",
        attackBonus: 4,
        damage: [{ dice: "1d4", mod: 2, type: "slashing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "bonus",
        finesse: true,
      },
    ],
    abilities: [],
    traits: [
      "Наскок (Pounce): при разбеге на 20 фт цель с СЛ 12 СИЛ падает ничком, а пантера может нанести укус бонусным действием.",
      "Лазание 40 фт и скрытность в тенях.",
    ],
    description: "Бесшумная и грациозная кошка с высочайшей скоростью и лазанием по стенам.",
    icon: "🐆",
  },
  {
    id: "giant_badger",
    name: "Гигантский барсук",
    nameEn: "Giant Badger",
    cr: 0.25,
    size: "medium",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 10,
    hpMax: 13,
    speed: 30,
    burrowSpeed: 10,
    abilityMods: { STR: 1, DEX: 0, CON: 2 },
    attacks: [
      {
        id: "badger_multi",
        name: "Мультиатака (Укус + Когти)",
        attackBonus: 3,
        damage: [
          { dice: "1d6", mod: 1, type: "piercing" },
          { dice: "2d4", mod: 1, type: "slashing" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Двойная атака: мощный укус и раздирание когтями.",
      },
      {
        id: "badger_bite",
        name: "Укус барсука",
        attackBonus: 3,
        damage: [{ dice: "1d6", mod: 1, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Мультиатака: совершает две атаки за одно Действие.", "Рытье земли (Burrow) 10 фт."],
    description: "Неприхотливый зверь с двумя атаками за ход и способностью закапываться под землю.",
    icon: "🦡",
  },
  {
    id: "giant_lizard",
    name: "Гигантская ящерица",
    nameEn: "Giant Lizard",
    cr: 0.25,
    size: "large",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 12,
    hpMax: 19,
    speed: 30,
    climb: 30,
    abilityMods: { STR: 2, DEX: 1, CON: 1 },
    attacks: [
      {
        id: "lizard_bite",
        name: "Укус ящерицы",
        attackBonus: 4,
        damage: [{ dice: "1d8", mod: 2, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Паучье лазание: может передвигаться по стенам и потолкам без проверок."],
    description: "Крупная выносливая рептилия с большим запасом здоровья (19 HP) и лазанием.",
    icon: "🦎",
  },
  {
    id: "spider",
    name: "Паук-лазутчик",
    nameEn: "Spider",
    cr: 0,
    size: "tiny",
    type: "beast",
    minLevel: 2,
    moonDruidMinLevel: 2,
    ac: 12,
    hpMax: 1,
    speed: 20,
    climb: 20,
    abilityMods: { STR: -4, DEX: 2, CON: -1 },
    attacks: [
      {
        id: "tiny_bite",
        name: "Ядовитый укус",
        attackBonus: 4,
        damage: [{ dice: "1", mod: 0, type: "piercing" }, { dice: "1d4", mod: 0, type: "poison" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Крошечный размер (Tiny): идеален для скрытной разведки и проникновения в замочные скважины."],
    description: "Идеальная форма для незаметной разведки сквозь щели и решётки.",
    icon: "🕷️",
  },

  // ================= CR 1/2 (Доступны с 4 уровня / Плавание) =================
  {
    id: "black_bear",
    name: "Чёрный медведь",
    nameEn: "Black Bear",
    cr: 0.5,
    size: "medium",
    type: "beast",
    minLevel: 4,
    moonDruidMinLevel: 2,
    ac: 11,
    hpMax: 19,
    speed: 40,
    climb: 30,
    abilityMods: { STR: 2, DEX: 0, CON: 2 },
    attacks: [
      {
        id: "bbear_multi",
        name: "Мультиатака (Укус + Когти)",
        attackBonus: 4,
        damage: [
          { dice: "1d6", mod: 2, type: "piercing" },
          { dice: "2d4", mod: 2, type: "slashing" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Наносит удар когтями и челюстями.",
      },
    ],
    abilities: [],
    traits: ["Мультиатака: две опасные атаки за действие.", "Острый нюх."],
    description: "Крепкий лесной хищник с хорошим уроном и лазанием по деревьям.",
    icon: "🐻",
  },
  {
    id: "crocodile",
    name: "Крокодил",
    nameEn: "Crocodile",
    cr: 0.5,
    size: "large",
    type: "beast",
    minLevel: 4,
    moonDruidMinLevel: 2,
    swim: true,
    swimSpeed: 30,
    ac: 12,
    hpMax: 19,
    speed: 20,
    abilityMods: { STR: 2, DEX: 0, CON: 1 },
    attacks: [
      {
        id: "croc_bite",
        name: "Мёртвая хватка",
        attackBonus: 4,
        damage: [{ dice: "1d10", mod: 2, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "При попадании цель захвачена (grappled, СЛ 12) и опутана до освобождения.",
      },
    ],
    abilities: [],
    traits: ["Захват челюстями (Grapple).", "Задержка дыхания до 15 минут.", "Плавание 30 фт."],
    description: "Водный охотник с мощным укусом, сковывающим движение противника.",
    icon: "🐊",
  },

  // ================= CR 1 (Круг Луны с 2 ур / Базовый с 8 ур / Полёт) =================
  {
    id: "brown_bear",
    name: "Бурый медведь",
    nameEn: "Brown Bear",
    cr: 1,
    size: "large",
    type: "beast",
    minLevel: 8,
    moonDruidOnly: true,
    moonDruidMinLevel: 2,
    ac: 11,
    hpMax: 34,
    speed: 40,
    climb: 30,
    abilityMods: { STR: 4, DEX: 0, CON: 3 },
    attacks: [
      {
        id: "bb_multi",
        name: "Мультиатака медведя",
        attackBonus: 6,
        damage: [
          { dice: "1d8", mod: 4, type: "piercing" },
          { dice: "2d6", mod: 4, type: "slashing" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Совершает укус (1к8+4) и сокрушительный удар когтями (2к6+4).",
      },
      {
        id: "bb_bite",
        name: "Укус",
        attackBonus: 6,
        damage: [{ dice: "1d8", mod: 4, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
      {
        id: "bb_claws",
        name: "Когти",
        attackBonus: 6,
        damage: [{ dice: "2d6", mod: 4, type: "slashing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: [
      "Огромный запас здоровья: 34 HP в форме зверя!",
      "Мультиатака: наносит суммарно до 1к8 + 2к6 + 8 урона за раунд.",
      "Острый нюх.",
    ],
    description: "Грозный и невероятно выносливый танк ближнего боя с сокрушительным уроном.",
    icon: "🐻",
  },
  {
    id: "dire_wolf",
    name: "Лютоволк",
    nameEn: "Dire Wolf",
    cr: 1,
    size: "large",
    type: "beast",
    minLevel: 8,
    moonDruidOnly: true,
    moonDruidMinLevel: 2,
    ac: 14,
    hpMax: 37,
    speed: 50,
    abilityMods: { STR: 3, DEX: 2, CON: 2 },
    attacks: [
      {
        id: "dwolf_bite",
        name: "Сокрушительный укус",
        attackBonus: 5,
        damage: [{ dice: "2d6", mod: 3, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Урон 2к6+3. Цель совершает спасбросок СИЛ (СЛ 13) или сбивается с ног (prone).",
      },
    ],
    abilities: [],
    traits: [
      "Стайная тактика: постоянное Преимущество на атаки рядом с союзником.",
      "Сбивание с ног: роняет противника на землю при каждом попадании (СЛ 13).",
      "Скорость 50 фт и 37 HP!",
    ],
    description: "Исполинский волк, сочетающий колоссальную скорость, здоровье и контроль врагов.",
    icon: "🐺",
  },
  {
    id: "giant_spider",
    name: "Гигантский паук",
    nameEn: "Giant Spider",
    cr: 1,
    size: "large",
    type: "beast",
    minLevel: 8,
    moonDruidOnly: true,
    moonDruidMinLevel: 2,
    ac: 14,
    hpMax: 26,
    speed: 30,
    climb: 30,
    abilityMods: { STR: 2, DEX: 3, CON: 1 },
    attacks: [
      {
        id: "gspider_bite",
        name: "Смертоносный ядовитый укус",
        attackBonus: 5,
        damage: [
          { dice: "1d8", mod: 3, type: "piercing" },
          { dice: "2d8", mod: 0, type: "poison" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "1к8+3 колющего + 2к8 яда (Спасбросок ТЕЛ СЛ 11 на половину урона от яда).",
      },
      {
        id: "gspider_web",
        name: "Выстрел паутиной",
        attackBonus: 5,
        damage: [],
        kind: "ranged",
        range: { normal: 30, long: 60 },
        actionCost: "action",
        description: "Дальнобойная атака: цель опутана (restrained). Спасбросок СИЛ СЛ 12 для освобождения.",
      },
    ],
    abilities: [],
    traits: [
      "Паучье лазание (Spider Climb): игнорирует трудности рельефа.",
      "Выстрел паутиной (Web): обездвиживает опасных стрелков и магов на дистанции.",
      "Тяжелый урон ядом (2d8).",
    ],
    description: "Тактический хищник с возможностью обездвиживать цели паутиной и травить ядом.",
    icon: "🕷️",
  },
  {
    id: "giant_hyena",
    name: "Гигантская гиена",
    nameEn: "Giant Hyena",
    cr: 1,
    size: "large",
    type: "beast",
    minLevel: 8,
    moonDruidOnly: true,
    moonDruidMinLevel: 2,
    ac: 12,
    hpMax: 45,
    speed: 50,
    abilityMods: { STR: 3, DEX: 2, CON: 2 },
    attacks: [
      {
        id: "ghyena_bite",
        name: "Укус гиены",
        attackBonus: 5,
        damage: [{ dice: "2d6", mod: 3, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: [
      "Рекордные 45 HP на 2 уровне!",
      "Ярость (Rampage): когда опускает врага до 0 HP, может бонусным действием переместиться на пол-скорости и совершить укус.",
    ],
    description: "Живучий гигант с 45 HP и цепной яростью при добивании противников.",
    icon: "🐕",
  },
  {
    id: "giant_eagle",
    name: "Гигантский орёл",
    nameEn: "Giant Eagle",
    cr: 1,
    size: "large",
    type: "beast",
    minLevel: 8,
    moonDruidMinLevel: 8,
    fly: true,
    flySpeed: 80,
    ac: 13,
    hpMax: 26,
    speed: 10,
    abilityMods: { STR: 3, DEX: 3, CON: 1 },
    attacks: [
      {
        id: "geagle_multi",
        name: "Мультиатака (Клюв + Когти)",
        attackBonus: 5,
        damage: [
          { dice: "1d6", mod: 3, type: "piercing" },
          { dice: "2d6", mod: 3, type: "slashing" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Полёт 80 фт: абсолютное превосходство в воздухе.", "Острое зрение."],
    description: "Величественная летающая форма с невероятной скоростью полёта 80 фт.",
    icon: "🦅",
  },

  // ================= CR 2 - 3 (Круг Луны с 6-9 уровней) =================
  {
    id: "cave_bear",
    name: "Пещерный / Полярный медведь",
    nameEn: "Cave / Polar Bear",
    cr: 2,
    size: "large",
    type: "beast",
    minLevel: 9,
    moonDruidOnly: true,
    moonDruidMinLevel: 6,
    ac: 12,
    hpMax: 42,
    speed: 40,
    swimSpeed: 30,
    abilityMods: { STR: 5, DEX: 0, CON: 3 },
    attacks: [
      {
        id: "cbear_multi",
        name: "Яростная мультиатака",
        attackBonus: 7,
        damage: [
          { dice: "1d8", mod: 5, type: "piercing" },
          { dice: "2d6", mod: 5, type: "slashing" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Мультиатака с бонусом атаки +7 и уроном 1к8+5 и 2к6+5!", "Плавание 30 фт, Тёмное зрение."],
    description: "Массивный северный хищник с сокрушительной физической силой (+5).",
    icon: "🐻‍❄️",
  },
  {
    id: "saber_toothed_tiger",
    name: "Саблезубый тигр",
    nameEn: "Saber-Toothed Tiger",
    cr: 2,
    size: "large",
    type: "beast",
    minLevel: 9,
    moonDruidOnly: true,
    moonDruidMinLevel: 6,
    ac: 12,
    hpMax: 52,
    speed: 40,
    abilityMods: { STR: 4, DEX: 2, CON: 2 },
    attacks: [
      {
        id: "stiger_bite",
        name: "Укус саблезуба",
        attackBonus: 6,
        damage: [{ dice: "1d10", mod: 4, type: "piercing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
      {
        id: "stiger_claws",
        name: "Удар когтями",
        attackBonus: 6,
        damage: [{ dice: "2d6", mod: 4, type: "slashing" }],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: ["Наскок (Pounce): при разбеге 20 фт роняет цель с СЛ 14 СИЛ и наносит укус бонусным действием.", "52 HP!"],
    description: "Древний охотник с длинными клыками и запасом здоровья 52 HP.",
    icon: "🐯",
  },
  {
    id: "giant_scorpion",
    name: "Гигантский скорпион",
    nameEn: "Giant Scorpion",
    cr: 3,
    size: "large",
    type: "beast",
    minLevel: 10,
    moonDruidOnly: true,
    moonDruidMinLevel: 9,
    ac: 15,
    hpMax: 52,
    speed: 40,
    abilityMods: { STR: 2, DEX: 1, CON: 2 },
    attacks: [
      {
        id: "gscorp_multi",
        name: "Тройная мультиатака (2 Клешни + Жало)",
        attackBonus: 4,
        damage: [
          { dice: "1d8", mod: 2, type: "bludgeoning" },
          { dice: "1d8", mod: 2, type: "bludgeoning" },
          { dice: "1d10", mod: 2, type: "piercing" },
          { dice: "4d10", mod: 0, type: "poison" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "2 удара клешнями с захватом + смертельное жало на 1к10+2 и 4к10 яда (СЛ 12 ТЕЛ на половину).",
      },
    ],
    abilities: [],
    traits: ["Тройная мультиатака: наносит сокрушительный яд 4к10!", "КД 15 (прочный панцирь)."],
    description: "Бронированный ужас с тремя атаками и колоссальным ядовитым уроном.",
    icon: "🦂",
  },

  // ================= CR 5 (Стихийный дикий облик с 10 уровня) =================
  {
    id: "fire_elemental",
    name: "Элементаль Огня",
    nameEn: "Fire Elemental",
    cr: 5,
    size: "large",
    type: "elemental",
    minLevel: 10,
    moonDruidOnly: true,
    moonDruidMinLevel: 10,
    ac: 13,
    hpMax: 102,
    speed: 50,
    abilityMods: { STR: 0, DEX: 3, CON: 3 },
    attacks: [
      {
        id: "felem_multi",
        name: "Огненное касание (×2)",
        attackBonus: 6,
        damage: [
          { dice: "2d6", mod: 3, type: "fire" },
          { dice: "2d6", mod: 3, type: "fire" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Два пылающих удара по 2к6+3 огня каждый.",
      },
    ],
    abilities: [],
    traits: [
      "102 HP и скорость 50 фт!",
      "Огненное тело: существа, коснувшиеся элементаля или начавшие ход рядом, загораются (1d10 огня).",
      "Иммунитет к огню, яду, параличу, сбиванию с ног.",
    ],
    description: "Пылающее воплощение первородного пламени с 102 HP.",
    icon: "🔥",
  },
  {
    id: "water_elemental",
    name: "Элементаль Воды",
    nameEn: "Water Elemental",
    cr: 5,
    size: "large",
    type: "elemental",
    minLevel: 10,
    moonDruidOnly: true,
    moonDruidMinLevel: 10,
    ac: 14,
    hpMax: 114,
    speed: 30,
    swimSpeed: 90,
    abilityMods: { STR: 4, DEX: 2, CON: 4 },
    attacks: [
      {
        id: "welem_multi",
        name: "Водяной вал (×2)",
        attackBonus: 7,
        damage: [
          { dice: "2d8", mod: 4, type: "bludgeoning" },
          { dice: "2d8", mod: 4, type: "bludgeoning" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
        description: "Два сокрушительных водяных удара по 2к8+4 урона каждый.",
      },
    ],
    abilities: [],
    traits: [
      "114 HP и плавание 90 фт!",
      "Захлестывание (Whelm): затягивает до двух существ внутрь себя, лишая воздуха.",
      "Сопротивление к немагическому дробящему, колющему и рубящему урону.",
    ],
    description: "Несокрушимая водяная стихия с 114 HP и сопротивлением к физическому урону.",
    icon: "🌊",
  },
  {
    id: "air_elemental",
    name: "Элементаль Воздуха",
    nameEn: "Air Elemental",
    cr: 5,
    size: "large",
    type: "elemental",
    minLevel: 10,
    moonDruidOnly: true,
    moonDruidMinLevel: 10,
    ac: 15,
    hpMax: 90,
    speed: 10,
    fly: true,
    flySpeed: 90,
    abilityMods: { STR: 2, DEX: 5, CON: 2 },
    attacks: [
      {
        id: "aelem_multi",
        name: "Удар вихря (×2)",
        attackBonus: 8,
        damage: [
          { dice: "2d8", mod: 5, type: "bludgeoning" },
          { dice: "2d8", mod: 5, type: "bludgeoning" },
        ],
        kind: "melee",
        range: { normal: 5 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: [
      "Полёт 90 фт (парение) и КД 15!",
      "Смерч (Whirlwind): закручивает врагов, нанося 3d8+2 урона и отбрасывая на 20 фт.",
      "Бестелесное перемещение сквозь клетки существ без провокации атак.",
    ],
    description: "Стремительный ураган со скоростью полёта 90 фт и способностью крушить толпы врагов.",
    icon: "🌪️",
  },
  {
    id: "earth_elemental",
    name: "Элементаль Земли",
    nameEn: "Earth Elemental",
    cr: 5,
    size: "large",
    type: "elemental",
    minLevel: 10,
    moonDruidOnly: true,
    moonDruidMinLevel: 10,
    ac: 17,
    hpMax: 126,
    speed: 30,
    burrowSpeed: 30,
    abilityMods: { STR: 5, DEX: -1, CON: 5 },
    attacks: [
      {
        id: "eelem_multi",
        name: "Каменный таран (×2)",
        attackBonus: 8,
        damage: [
          { dice: "2d10", mod: 5, type: "bludgeoning" },
          { dice: "2d10", mod: 5, type: "bludgeoning" },
        ],
        kind: "melee",
        range: { normal: 10 },
        actionCost: "action",
      },
    ],
    abilities: [],
    traits: [
      "126 HP и КД 17!",
      "Хождение сквозь камень (Earth Glide): проходит сквозь твердую породу и стены.",
      "Сопротивление к немагическому физическому урону.",
    ],
    description: "Несокрушимая живая скала с максимальным запасом здоровья (126 HP) и КД 17.",
    icon: "🪨",
  },
];

/** Получить доступные формы зверя для друида по его уровню и подклассу */
export function getAvailableBeastForms(level: number, isMoonDruid = false): BeastForm[] {
  return BEAST_FORMS.filter((form) => {
    if (form.type === "elemental") {
      return isMoonDruid && level >= 10;
    }
    if (isMoonDruid) {
      const minLvl = form.moonDruidMinLevel ?? form.minLevel;
      if (level < minLvl) return false;
      // Ограничение полета до 8 уровня даже у Луны
      if (form.fly && level < 8) return false;
      return true;
    }
    // Базовый друид
    if (form.moonDruidOnly) return false;
    if (level < form.minLevel) return false;
    if (form.swim && level < 4) return false;
    if (form.fly && level < 8) return false;
    return true;
  });
}

/** Найти форму по ID */
export function getBeastFormById(formId: string): BeastForm | undefined {
  return BEAST_FORMS.find((f) => f.id === formId);
}
