import type { CharacterPreset, Combatant, Attack, CombatAbility, ActionParameters } from "./types";
import { getAllSRDMonsters } from "./srd/adapter";

/**
 * Аутентичные пресеты персонажей и бестиарий D&D 5e,
 * полностью синхронизированные с текущими листами кампании пользователя.
 */
export const CAMPAIGN_HEROES_PRESETS: CharacterPreset[] = [
  // ==========================================
  // ТЕСТОВЫЙ МАГ И ДРУИД (3-Й КРУГ И ДИКИЙ ОБЛИК)
  // ==========================================
  {
    id: "preset-eldrin-mage",
    name: "Эльдрин (Архимаг 3-го круга)",
    type: "player",
    color: "#8b5cf6",
    className: "Волшебник",
    level: 6,
    size: "medium",
    hpMax: 38,
    ac: 15,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: -1, DEX: 2, CON: 2, INT: 4, WIS: 1, CHA: 0 },
    saves: {
      INT: { prof: true, mod: 7 },
      WIS: { prof: true, mod: 4 },
      CON: { prof: false, mod: 2 },
    },
    profBonus: 3,
    attacks: [
      {
        id: "eldrin_staff",
        name: "Посох силы",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 2,
        damage: [{ dice: "1d6", mod: -1, type: "bludgeoning" }],
        actionCost: "action",
        description: "Удар магическим посохом.",
      },
    ],
    spells: {
      slots: {
        "1": { max: 4, used: 0 },
        "2": { max: 3, used: 0 },
        "3": { max: 3, used: 0 },
      },
      known: [
        "spell_117", // Огненный шар (Fireball)
        "spell_191", // Молния (Lightning Bolt)
        "spell_145", // Ускорение (Haste)
        "spell_264", // Замедление (Slow)
        "spell_124", // Полет (Fly)
        "spell_304", // Вампирское прикосновение (Vampiric Touch)
        "spell_111", // Страх (Fear)
        "spell_263", // Метель (Sleet Storm)
        "spell_156", // Гипнотический узор (Hypnotic Pattern)
        "spell_274", // Зловонное облако (Stinking Cloud)
        "spell_64",  // Контрзаклинание (Counterspell)
        "spell_84",  // Рассеивание магии (Dispel Magic)
        "spell_32",  // Мерцание (Blink)
        "spell_244", // Палящий луч (Scorching Ray)
        "spell_211", // Туманный шаг (Misty Step)
        "spell_209", // Зеркальный образ (Mirror Image)
        "spell_197", // Волшебная стрела (Magic Missile)
        "spell_193", // Доспехи мага (Mage Armor)
        "spell_258", // Щит (Shield)
        "spell_113", // Огненный снаряд (Fire Bolt)
        "spell_248", // Леденящее прикосновение (Chill Touch)
      ],
      prepared: [
        "spell_117",
        "spell_191",
        "spell_145",
        "spell_264",
        "spell_124",
        "spell_304",
        "spell_111",
        "spell_263",
        "spell_156",
        "spell_274",
        "spell_64",
        "spell_84",
        "spell_32",
        "spell_244",
        "spell_211",
        "spell_209",
        "spell_197",
        "spell_193",
        "spell_258",
        "spell_113",
        "spell_248",
      ],
      spellcastingAbility: "INT",
      spellSaveDC: 15,
      spellAttackBonus: 7,
    },
    abilities: [],
    description: "Могущественный волшебник 6-го уровня, владеющий всеми боевыми заклинаниями 3-го круга (Огненный шар, Молния, Ускорение, Замедление, Вампирское прикосновение, Страх, Метель, Полет и др.).",
    isTemplate: true,
    category: "heroes",
    tags: ["волшебник", "маг", "3 круг", "заклинатель", "огонь", "молния"],
  },
  {
    id: "preset-myra-druid",
    name: "Мира (Друид Круга Луны 6)",
    type: "player",
    color: "#059669",
    className: "Друид (Круг Луны)",
    level: 6,
    size: "medium",
    hpMax: 45,
    ac: 14,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 0, DEX: 2, CON: 2, INT: 1, WIS: 4, CHA: -1 },
    saves: {
      INT: { prof: true, mod: 4 },
      WIS: { prof: true, mod: 7 },
      CON: { prof: false, mod: 2 },
    },
    profBonus: 3,
    attacks: [
      {
        id: "myra_staff",
        name: "Деревянный посох",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 3,
        damage: [{ dice: "1d6", mod: 0, type: "bludgeoning" }],
        actionCost: "action",
        description: "Удар дубовым посохом друида.",
      },
    ],
    spells: {
      slots: {
        "1": { max: 4, used: 0 },
        "2": { max: 3, used: 0 },
        "3": { max: 3, used: 0 },
      },
      known: [
        "spell_259", // Дубинка (Shillelagh)
        "spell_146", // Раскаленный металл (Heat Metal)
        "spell_37",  // Призыв молнии (Call Lightning)
        "spell_213", // Лунный луч (Moonbeam)
        "spell_153", // Удержание гуманоида (Hold Person)
      ],
      prepared: [
        "spell_259",
        "spell_146",
        "spell_37",
        "spell_213",
        "spell_153",
      ],
      spellcastingAbility: "WIS",
      spellSaveDC: 15,
      spellAttackBonus: 7,
    },
    abilities: [
      {
        id: "combat_wild_shape",
        name: "Боевой дикий облик",
        usesMax: 2,
        usesUsed: 0,
        refresh: "short",
        parameters: {
          name: "Боевой дикий облик",
          type: "ability",
          actionCost: "bonus",
          range: { type: "self" },
          damage: [],
          targeting: "self",
          description: "Бонусным действием превращается в опасного зверя (Бурый медведь, Лютоволк, Гигантский паук, Пещерный медведь, Саблезубый тигр) с пулом здоровья зверя.",
        },
      },
    ],
    description: "Хранительница дикой природы 6-го уровня. Способна бонусным действием принимать форму свирепого медведя, волка или тигра, сохраняя концентрацию на заклинаниях.",
    isTemplate: true,
    category: "heroes",
    tags: ["друид", "круг луны", "дикий облик", "звери", "заклинатель"],
  },

  // ==========================================
  // ГЕРОИ КАМПАНИИ (ИГРОКИ)
  // ==========================================
  {
    id: "preset-silas-vane",
    name: "Силас Вейн (Следопыт 4)",
    type: "player",
    color: "#10b981",
    className: "Следопыт",
    level: 4,
    size: "medium",
    hpMax: 42,
    ac: 17,
    speed: 30,
    dexMod: 4,
    initiativeMod: 4,
    attacksPerAction: 1,
    abilityMods: { STR: -1, DEX: 4, CON: 2, INT: 0, WIS: 2, CHA: 0 },
    saves: {
      STR: { prof: true, mod: 1 },
      DEX: { prof: true, mod: 6 },
    },
    profBonus: 2,
    attacks: [
      {
        id: "silas_xbow_main",
        name: "Ручной арбалет (Действие +8)",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 8,
        damage: [{ dice: "1d6", mod: 6, type: "piercing" }],
        actionCost: "action",
        description: "Выстрел из ручного арбалета с чертой «Эксперт в арбалетах» (+8 к атаке, 1к6+6 колющий).",
      },
      {
        id: "silas_xbow_bonus",
        name: "Ручной арбалет (Бонусное +8)",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 8,
        damage: [{ dice: "1d6", mod: 6, type: "piercing" }],
        actionCost: "bonus",
        description: "Дополнительный выстрел бонусным действием от «Эксперта в арбалетах».",
      },
      {
        id: "silas_xbow_fire",
        name: "Зажигательный болт (+8 / +1d4 огня)",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 8,
        damage: [
          { dice: "1d6", mod: 6, type: "piercing" },
          { dice: "1d4", mod: 0, type: "fire" },
        ],
        actionCost: "action",
        description: "Специальный зажигательный болт: 1к6+6 колющего + 1к4 урона огнем.",
      },
      {
        id: "silas_shortsword",
        name: "Короткий меч",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 6,
        damage: [{ dice: "1d6", mod: 4, type: "piercing" }],
        actionCost: "action",
        description: "Фехтовальное оружие ближнего боя (+6 к атаке, 1к6+4 колющий).",
      },
    ],
    spells: {
      slots: { 1: { max: 4, used: 0 } },
      known: ["Метка охотника", "Маскировка", "Лечение ран"],
      prepared: ["Метка охотника", "Маскировка", "Лечение ран"],
      spellcastingAbility: "WIS",
      spellSaveDC: 12,
      spellAttackBonus: 4,
    },
    abilities: [
      {
        id: "crossbow_expert",
        name: "Эксперт в арбалетах (Crossbow Expert)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Эксперт в арбалетах",
          type: "ability",
          actionCost: "free",
          range: { type: "self" },
          targeting: "self",
          description: "Игнорирует свойство перезарядки арбалетов, не получает помехи от врагов в пределах 5 фт, позволяет стрелять бонусным действием.",
        },
      },
      {
        id: "water_walking",
        name: "Сапоги Водохождения (Бег по воде)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Сапоги Водохождения",
          type: "ability",
          actionCost: "free",
          range: { type: "self" },
          targeting: "self",
          description: "Магические сапоги позволяют свободно перемещаться по поверхности воды, словно по твердой земле.",
        },
      },
    ],
    description: "Меткий следопыт 4 уровня с ручным арбалетом, знанием магии природы и волшебными сапогами водохождения.",
    isTemplate: true,
    category: "heroes",
    tags: ["следопыт", "герой", "арбалет", "дальний бой", "кампания"],
  },

  {
    id: "preset-nyx",
    name: "Никс (Плут 4 / Убийца)",
    type: "player",
    color: "#8b5cf6",
    className: "Плут (Убийца)",
    level: 4,
    size: "medium",
    hpMax: 29,
    ac: 17,
    speed: 30,
    dexMod: 4,
    initiativeMod: 4,
    attacksPerAction: 1,
    abilityMods: { STR: -1, DEX: 4, CON: 2, INT: 1, WIS: 1, CHA: 0 },
    saves: {
      DEX: { prof: true, mod: 6 },
      INT: { prof: true, mod: 3 },
    },
    profBonus: 2,
    attacks: [
      {
        id: "nyx_moonlit_blade",
        name: "«Клинок Лунной Тени» (+1)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 7,
        damage: [
          { dice: "1d6", mod: 5, type: "piercing" },
          { dice: "1d6", mod: 0, type: "cold" },
        ],
        actionCost: "action",
        description: "Магический клинок +1: наносит 1к6+5 колющего урона + 1к6 дополнительного урона холодом.",
      },
      {
        id: "nyx_sword_off",
        name: "Обсидиановый меч (Вторая рука)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 6,
        damage: [{ dice: "1d6", mod: 0, type: "piercing" }],
        actionCost: "bonus",
        description: "Атака вторым оружием бонусным действием (1к6 колющий).",
      },
      {
        id: "nyx_dagger",
        name: "Кинжал (Бросок)",
        kind: "ranged",
        range: { normal: 20, long: 60 },
        attackBonus: 6,
        damage: [{ dice: "1d4", mod: 4, type: "piercing" }],
        actionCost: "action",
        description: "Бросок кинжала на 20/60 фт (+6 к атаке, 1к4+4 колющий).",
      },
    ],
    spells: {
      slots: {},
      known: [],
      prepared: [],
    },
    abilities: [
      {
        id: "nyx_sneak",
        name: "Скрытая атака (2d6)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Скрытая атака",
          type: "ability",
          actionCost: "free",
          damage: [{ dice: "2d6", mod: 0, type: "piercing" }],
          description: "Наносит дополнительные 2к6 урона при наличии преимущества или союзника в 5 фт от цели.",
        },
      },
      {
        id: "nyx_assassinate",
        name: "Ликвидация (Assassinate)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Ликвидация",
          type: "ability",
          actionCost: "free",
          description: "Преимущество на атаки по существам, еще не сделавшим ход в бою, и автоматический критический удар при неожиданности.",
        },
      },
      {
        id: "nyx_cunning_dash",
        name: "Хитрое действие: Рывок",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Хитрое действие: Рывок",
          type: "ability",
          actionCost: "bonus",
          selfEffects: [{ condition: "dashing", durationRounds: 1 }],
          description: "Совершает Рывок в качестве бонусного действия, удваивая скорость на текущий ход.",
        },
      },
      {
        id: "nyx_cunning_disengage",
        name: "Хитрое действие: Отход",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Хитрое действие: Отход",
          type: "ability",
          actionCost: "bonus",
          selfEffects: [{ condition: "disengaging", durationRounds: 1 }],
          description: "Совершает Отход бонусным действием, избегая провоцированных атак.",
        },
      },
      {
        id: "nyx_cunning_hide",
        name: "Хитрое действие: Засада",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Хитрое действие: Засада",
          type: "ability",
          actionCost: "bonus",
          selfEffects: [{ condition: "hidden", durationRounds: 10 }],
          description: "Совершает проверку Скрытности бонусным действием, чтобы спрятаться от врагов.",
        },
      },
    ],
    description: "Смертоносный плут-убийца 4 уровня с парными клинками Лунной Тени, скрытной атакой 2к6 и хитрыми действиями.",
    isTemplate: true,
    category: "heroes",
    tags: ["плут", "убийца", "герой", "скрытность", "кампания"],
  },

  {
    id: "preset-torbor",
    name: "Торбор (Друид 4 / Тортл)",
    type: "player",
    color: "#059669",
    className: "Друид (Круг Луны)",
    level: 4,
    size: "medium",
    hpMax: 36,
    ac: 19,
    speed: 30,
    dexMod: 0,
    initiativeMod: 0,
    attacksPerAction: 1,
    abilityMods: { STR: 2, DEX: 0, CON: 2, INT: 0, WIS: 4, CHA: 0 },
    saves: {
      INT: { prof: true, mod: 2 },
      WIS: { prof: true, mod: 6 },
    },
    profBonus: 2,
    attacks: [
      {
        id: "torbor_withered_shillelagh",
        name: "«Чёрный Вяз» (с Дубинкой +7)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 7,
        damage: [{ dice: "1d8", mod: 5, type: "bludgeoning" }],
        actionCost: "action",
        description: "Древний посох «Чёрный Вяз», усиленный заклинанием «Дубинка»: атака от Мудрости +7, магический урон 1к8+5.",
      },
      {
        id: "torbor_withered_staff",
        name: "«Чёрный Вяз» (Обычный +5)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [{ dice: "1d8", mod: 3, type: "bludgeoning" }],
        actionCost: "action",
        description: "Обычный удар посохом «Чёрный Вяз» (+5 к атаке, 1к8+3 дробящий).",
      },
      {
        id: "shillelagh_attack",
        name: "Дубинка / Посох (Шиллейла)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 6,
        damage: [{ dice: "1d8", mod: 4, type: "bludgeoning" }],
        actionCost: "action",
        description: "Базовый магический удар с Дубинкой (1к8+4 дробящий).",
      },
    ],
    spells: {
      slots: {
        1: { max: 4, used: 0 },
        2: { max: 3, used: 0 },
      },
      known: [
        "Свет",
        "Указание",
        "Терновый кнут",
        "Брызги яда",
        "Дубинка",
        "Лечащее слово",
        "Опутывание",
        "Ледяной кинжал",
        "Поглощение стихий",
        "Раскаленный металл",
        "Удержание личности",
        "Лунный луч",
        "Малое восстановление",
        "Дубовая кора",
        "Бесследное передвижение",
        "Раскалить доспех (2d8)",
      ],
      prepared: [
        "Свет",
        "Указание",
        "Терновый кнут",
        "Брызги яда",
        "Дубинка",
        "Лечащее слово",
        "Опутывание",
        "Ледяной кинжал",
        "Поглощение стихий",
        "Раскаленный металл",
        "Удержание личности",
        "Лунный луч",
        "Малое восстановление",
        "Дубовая кора",
        "Бесследное передвижение",
        "Раскалить доспех (2d8)",
      ],
      spellcastingAbility: "WIS",
      spellSaveDC: 14,
      spellAttackBonus: 6,
    },
    abilities: [
      {
        id: "torbor_wild_shape_croc",
        name: "Дикий облик: Крокодил (19 HP, Захват)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Дикий облик: Крокодил",
          type: "ability",
          actionCost: "bonus",
          selfHeal: { dice: "0d0", mod: 19 },
          selfEffects: [{ condition: "wild_shape", durationRounds: 600 }],
          description: "Превращение в Крокодила (19 HP, AC 12, укус 1к10+2 с автоматическим захватом цели, плавание).",
        },
      },
      {
        id: "torbor_wild_shape_shark",
        name: "Дикий облик: Рифовая акула (22 HP, Плавание 40)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Дикий облик: Рифовая акула",
          type: "ability",
          actionCost: "bonus",
          selfHeal: { dice: "0d0", mod: 22 },
          selfEffects: [{ condition: "wild_shape", durationRounds: 600 }],
          description: "Превращение в Рифовую акулу (22 HP, AC 12, скорость плавания 40 фт, тактика стаи, укус 1к8+2).",
        },
      },
      {
        id: "torbor_wild_shape_bear",
        name: "Дикий облик: Черный медведь (19 HP, 2 атаки)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Дикий облик: Черный медведь",
          type: "ability",
          actionCost: "bonus",
          selfHeal: { dice: "0d0", mod: 19 },
          selfEffects: [{ condition: "wild_shape", durationRounds: 600 }],
          description: "Превращение в Черного медведя (19 HP, AC 11, мультиатака укусом и когтями).",
        },
      },
      {
        id: "torbor_shell",
        name: "Укрытие в панцире (+4 КД = 23 AC)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Укрытие в панцире",
          type: "ability",
          actionCost: "action",
          description: "Тортл втягивает голову и конечности в панцирь, получая +4 к КД (итого 23 КД) и преимущество на спасброски Силы и Телосложения.",
        },
      },
    ],
    description: "Друид-тортл 4 уровня (Круг Луны). Естественная броня панциря 19 AC, мощные заклинания природы, посох «Чёрный Вяз» и боевые формы зверей.",
    isTemplate: true,
    category: "heroes",
    tags: ["друид", "тортл", "круг луны", "дикий облик", "танк", "кампания"],
  },

  {
    id: "preset-varis",
    name: "Варис (Воин 4 / Мастер оружия)",
    type: "player",
    color: "#ef4444",
    className: "Воин",
    level: 4,
    size: "medium",
    hpMax: 38,
    ac: 18,
    speed: 30,
    dexMod: 1,
    initiativeMod: 1,
    attacksPerAction: 1,
    abilityMods: { STR: 3, DEX: 1, CON: 3, INT: 0, WIS: 1, CHA: -1 },
    saves: {
      STR: { prof: true, mod: 5 },
      CON: { prof: true, mod: 5 },
    },
    profBonus: 2,
    attacks: [
      {
        id: "varis-longsword",
        name: "Длинный меч (Одноручный)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [{ dice: "1d8", mod: 3, type: "slashing" }],
        actionCost: "action",
        description: "Удар длинным мечом в одной руке (+5 к атаке, 1к8+3 рубящий).",
      },
      {
        id: "varis-longsword-twohanded",
        name: "Длинный меч (Двуручный хват)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [{ dice: "1d10", mod: 3, type: "slashing" }],
        actionCost: "action",
        description: "Удар длинным мечом двумя руками (+5 к атаке, 1к10+3 рубящий).",
      },
      {
        id: "varis-javelin",
        name: "Метательное копьё",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 5,
        damage: [{ dice: "1d6", mod: 3, type: "piercing" }],
        actionCost: "action",
        description: "Бросок копья (+5 к атаке, 1к6+3 колющий, 30/120 фт).",
      },
    ],
    spells: {
      slots: {},
      known: [],
      prepared: [],
    },
    abilities: [
      {
        id: "varis-second-wind",
        name: "Второе дыхание",
        usesMax: 1,
        usesUsed: 0,
        refresh: "short",
        parameters: {
          name: "Второе дыхание",
          type: "ability",
          actionCost: "bonus",
          selfHeal: { dice: "1d10", mod: 4 },
          description: "Бонусным действием восстанавливает 1к10 + 4 HP (1 раз за короткий отдых).",
        },
      },
      {
        id: "varis-action-surge",
        name: "Порыв к действию",
        usesMax: 1,
        usesUsed: 0,
        refresh: "short",
        parameters: {
          name: "Порыв к действию",
          type: "ability",
          actionCost: "free",
          grantsExtraAction: true,
          description: "Получает 1 дополнительное Действие в текущий ход (1 раз за короткий отдых).",
        },
      },
    ],
    description: "Закаленный воин 4 уровня в латах и со щитом (18 AC), владеющий длинным мечом и боевыми приемами.",
    isTemplate: true,
    category: "heroes",
    tags: ["воин", "герой", "танк", "ближний бой", "кампания"],
  },

  // ==========================================
  // ВРАГИ КАМПАНИИ (КУЛЬТИСТЫ И ГЛУБИНЫ)
  // ==========================================
  {
    id: "preset-ash-priest",
    name: "Пепельный Глубинный Жрец",
    type: "enemy",
    color: "#0284c7",
    className: "Жрец Глубин",
    level: 4,
    cr: "2",
    size: "medium",
    hpMax: 35,
    ac: 14,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 1, DEX: 2, CON: 2, INT: 1, WIS: 3, CHA: 2 },
    profBonus: 2,
    attacks: [
      {
        id: "priest_trident",
        name: "Костяной трезубец глубин",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [
          { dice: "1d6", mod: 2, type: "piercing" },
          { dice: "1d6", mod: 0, type: "cold" },
        ],
        actionCost: "action",
        description: "Удар трезубцем из костей морских чудовищ: 1к6+2 колющего + 1к6 урона холодом.",
      },
    ],
    spells: {
      slots: {
        1: { max: 4, used: 0 },
        2: { max: 3, used: 0 },
      },
      known: ["Ледяной шквал", "Раскаленный металл", "Удержание личности", "Свет"],
      prepared: ["Ледяной шквал", "Раскаленный металл", "Удержание личности", "Свет"],
      spellcastingAbility: "WIS",
      spellSaveDC: 13,
      spellAttackBonus: 5,
    },
    abilities: [],
    description: "Жрец темного культа глубин, вооруженный костяным морозным трезубцем и магией холода и контроля.",
    isTemplate: true,
    category: "monsters",
    tags: ["жрец", "враг", "босс", "культ", "кампания"],
  },

  {
    id: "preset-ash-triton",
    name: "Пепельный Тритон",
    type: "enemy",
    color: "#0d9488",
    className: "Воин Глубин",
    level: 2,
    cr: "1/2",
    size: "medium",
    hpMax: 20,
    ac: 13,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 2, DEX: 2, CON: 2, INT: 0, WIS: 1, CHA: 0 },
    profBonus: 2,
    attacks: [
      {
        id: "triton_spear",
        name: "Зазубренное костяное копье",
        kind: "melee",
        range: { normal: 5, long: 20 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "piercing" }],
        actionCost: "action",
        description: "Атака копьем в ближнем бою или бросок на 20 фт (+4 к атаке, 1к6+2 колющий).",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [],
    description: "Пепельный тритон-страж культа глубин, вооруженный зазубренным костяным копьем.",
    isTemplate: true,
    category: "monsters",
    tags: ["тритон", "враг", "миньон", "кампания"],
  },

  {
    id: "preset-corsair",
    name: "Корсар Культа",
    type: "enemy",
    color: "#b91c1c",
    className: "Плут-Корсар",
    level: 2,
    cr: "1/2",
    size: "medium",
    hpMax: 16,
    ac: 13,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 1, DEX: 2, CON: 1, INT: 0, WIS: 0, CHA: 0 },
    profBonus: 2,
    attacks: [
      {
        id: "corsair_cutlass",
        name: "Абордажный тесак",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "slashing" }],
        actionCost: "action",
        description: "Острый абордажный тесак (+4 к атаке, 1к6+2 рубящий).",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [],
    description: "Пират-наемник на службе культа, обученный абордажным схваткам.",
    isTemplate: true,
    category: "monsters",
    tags: ["корсар", "пират", "враг", "миньон", "кампания"],
  },

  // ==========================================
  // БЕСТИАРИЙ D&D 5E (КЛАССИЧЕСКИЕ МОНСТРЫ)
  // ==========================================
  {
    id: "preset-goblin",
    name: "Гоблин",
    type: "enemy",
    color: "#f59e0b",
    className: "Гоблиноид",
    level: 1,
    cr: "1/4",
    size: "small",
    hpMax: 7,
    ac: 15,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: -1, DEX: 2, CON: 0, INT: 0, WIS: -1, CHA: -1 },
    profBonus: 2,
    attacks: [
      {
        id: "goblin-scimitar",
        name: "Ятаган",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "slashing" }],
        actionCost: "action",
      },
      {
        id: "goblin-shortbow",
        name: "Короткий лук",
        kind: "ranged",
        range: { normal: 80, long: 320 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "piercing" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [
      {
        id: "nimble-escape",
        name: "Проворное бегство (Nimble Escape)",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Проворное бегство",
          type: "ability",
          actionCost: "bonus",
          selfEffects: [{ condition: "disengaging", durationRounds: 1 }],
          description: "Гоблин может совершать действие Отход или Засада бонусным действием в каждый свой ход.",
        },
      },
    ],
    description: "Хитрый маленький гуманоид, использующий засады и побеги через бонусные действия.",
    isTemplate: true,
    category: "monsters",
    tags: ["гоблин", "бестиарий", "cr 1/4", "гуманоид"],
  },

  {
    id: "preset-orc",
    name: "Орк-рубака",
    type: "enemy",
    color: "#dc2626",
    className: "Гуманоид (Орк)",
    level: 2,
    cr: "1/2",
    size: "medium",
    hpMax: 15,
    ac: 13,
    speed: 30,
    dexMod: 1,
    initiativeMod: 1,
    attacksPerAction: 1,
    abilityMods: { STR: 3, DEX: 1, CON: 3, INT: -2, WIS: 0, CHA: 0 },
    profBonus: 2,
    attacks: [
      {
        id: "orc-greataxe",
        name: "Двуручная секира",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [{ dice: "1d12", mod: 3, type: "slashing" }],
        actionCost: "action",
      },
      {
        id: "orc-javelin",
        name: "Дротик",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 5,
        damage: [{ dice: "1d6", mod: 3, type: "piercing" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [
      {
        id: "orc-aggressive",
        name: "Агрессивный напор",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Агрессивный напор",
          type: "ability",
          actionCost: "bonus",
          selfEffects: [{ condition: "dashing", durationRounds: 1 }],
          description: "Бонусным действием может переместиться на расстояние до своей скорости к видимому врагу.",
        },
      },
    ],
    description: "Яростный воин орков с сокрушительной секирой 1к12+3 и бонусом стремительного сближения.",
    isTemplate: true,
    category: "monsters",
    tags: ["орк", "бестиарий", "cr 1/2", "гуманоид"],
  },

  {
    id: "preset-skeleton",
    name: "Скелет-лучник",
    type: "enemy",
    color: "#94a3b8",
    className: "Нежить",
    level: 2,
    cr: "1/4",
    size: "medium",
    hpMax: 13,
    ac: 13,
    speed: 30,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 0, DEX: 2, CON: 2, INT: -2, WIS: -1, CHA: -3 },
    profBonus: 2,
    attacks: [
      {
        id: "skel-shortbow",
        name: "Короткий лук",
        kind: "ranged",
        range: { normal: 80, long: 320 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "piercing" }],
        actionCost: "action",
      },
      {
        id: "skel-shortsword",
        name: "Короткий меч",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 4,
        damage: [{ dice: "1d6", mod: 2, type: "piercing" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [],
    description: "Оживленный скелет, уязвимый к дробящему урону и невосприимчивый к ядам.",
    isTemplate: true,
    category: "monsters",
    tags: ["скелет", "нежить", "бестиарий", "cr 1/4"],
  },

  {
    id: "preset-zombie",
    name: "Зомби",
    type: "enemy",
    color: "#65a30d",
    className: "Нежить",
    level: 2,
    cr: "1/4",
    size: "medium",
    hpMax: 22,
    ac: 8,
    speed: 20,
    dexMod: -2,
    initiativeMod: -2,
    attacksPerAction: 1,
    abilityMods: { STR: 1, DEX: -2, CON: 3, INT: -4, WIS: -2, CHA: -3 },
    profBonus: 2,
    attacks: [
      {
        id: "zombie-slam",
        name: "Удар кулаком",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 3,
        damage: [{ dice: "1d6", mod: 1, type: "bludgeoning" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [],
    description: "Медлительный, но невероятно живучий оживший мертвец с чертой «Стойкость нежити».",
    isTemplate: true,
    category: "monsters",
    tags: ["зомби", "нежить", "бестиарий", "cr 1/4"],
  },

  {
    id: "preset-dire-wolf",
    name: "Лютый волк",
    type: "enemy",
    color: "#78716c",
    className: "Зверь",
    level: 3,
    cr: "1",
    size: "large",
    hpMax: 37,
    ac: 14,
    speed: 50,
    dexMod: 2,
    initiativeMod: 2,
    attacksPerAction: 1,
    abilityMods: { STR: 3, DEX: 2, CON: 2, INT: -4, WIS: 1, CHA: -2 },
    profBonus: 2,
    attacks: [
      {
        id: "wolf-bite",
        name: "Укус с опрокидыванием",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 5,
        damage: [{ dice: "2d6", mod: 3, type: "piercing" }],
        actionCost: "action",
        description: "Укус наносит 2к6+3 колющего урона. Если цель — существо, она должна пройти спасброск Силы СЛ 13 или упасть ничком.",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [
      {
        id: "pack-tactics",
        name: "Тактика стаи",
        usesMax: 99,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Тактика стаи",
          type: "ability",
          actionCost: "free",
          description: "Волк получает преимущество на броски атаки по существу, если хотя бы один из его дееспособных союзников находится в пределах 5 фт от цели.",
        },
      },
    ],
    description: "Грозный хищник большого размера со скоростью 50 фт, тактикой стаи и сбивающим с ног укусом.",
    isTemplate: true,
    category: "monsters",
    tags: ["волк", "зверь", "бестиарий", "cr 1", "большой"],
  },

  {
    id: "preset-ogre",
    name: "Огр-крушитель",
    type: "enemy",
    color: "#d97706",
    className: "Великан",
    level: 4,
    cr: "2",
    size: "large",
    hpMax: 59,
    ac: 11,
    speed: 40,
    dexMod: -1,
    initiativeMod: -1,
    attacksPerAction: 1,
    abilityMods: { STR: 4, DEX: -1, CON: 3, INT: -3, WIS: -2, CHA: -2 },
    profBonus: 2,
    attacks: [
      {
        id: "ogre-greatclub",
        name: "Огромная дубина",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 6,
        damage: [{ dice: "2d8", mod: 4, type: "bludgeoning" }],
        actionCost: "action",
        description: "Сокрушительный удар дубиной великана: 2к8+4 дробящего урона.",
      },
      {
        id: "ogre-javelin",
        name: "Огромное копьё (Бросок)",
        kind: "ranged",
        range: { normal: 30, long: 120 },
        attackBonus: 6,
        damage: [{ dice: "2d6", mod: 4, type: "piercing" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [],
    description: "Огромный тупоголовый великан (2×2 клетки, 59 HP), наносящий 2к8+4 урона каждым взмахом.",
    isTemplate: true,
    category: "monsters",
    tags: ["огр", "великан", "бестиарий", "cr 2", "большой"],
  },

  {
    id: "preset-red-dragon",
    name: "Молодой красный дракон",
    type: "enemy",
    color: "#b91c1c",
    className: "Дракон",
    level: 10,
    cr: "10",
    size: "large",
    hpMax: 178,
    ac: 18,
    speed: 40,
    dexMod: 0,
    initiativeMod: 0,
    attacksPerAction: 3,
    abilityMods: { STR: 6, DEX: 0, CON: 5, INT: 2, WIS: 1, CHA: 4 },
    saves: {
      DEX: { prof: true, mod: 4 },
      CON: { prof: true, mod: 9 },
      WIS: { prof: true, mod: 5 },
      CHA: { prof: true, mod: 8 },
    },
    profBonus: 4,
    attacks: [
      {
        id: "dragon-bite",
        name: "Укус дракона (+10 / 2d10+6 + 1d6 огня)",
        kind: "melee",
        range: { normal: 10 },
        attackBonus: 10,
        damage: [
          { dice: "2d10", mod: 6, type: "piercing" },
          { dice: "1d6", mod: 0, type: "fire" },
        ],
        actionCost: "action",
      },
      {
        id: "dragon-claw",
        name: "Когти (+10 / 2d6+6)",
        kind: "melee",
        range: { normal: 5 },
        attackBonus: 10,
        damage: [{ dice: "2d6", mod: 6, type: "slashing" }],
        actionCost: "action",
      },
    ],
    spells: { slots: {}, known: [] },
    abilities: [
      {
        id: "dragon-breath",
        name: "Огненное дыхание (16d6 огня, конус 30 фт)",
        usesMax: 1,
        usesUsed: 0,
        refresh: "turn",
        parameters: {
          name: "Огненное дыхание",
          type: "ability",
          actionCost: "action",
          range: { type: "cone", value: 30 },
          aoe: { shape: "cone", size: 30 },
          saveType: "DEX",
          saveDC: 17,
          damage: [{ dice: "16d6", mod: 0, type: "fire" }],
          description: "Дракон выдыхает огонь 30-футовым конусом. Спасбросок Ловкости СЛ 17 (половина урона при успехе).",
        },
      },
    ],
    description: "Легендарный хищник: 178 HP, 18 AC, мультиатака тремя ударами (укус и два когтя) и смертоносное Огненное дыхание 16к6.",
    isTemplate: true,
    category: "monsters",
    tags: ["дракон", "бестиарий", "cr 10", "босс", "большой"],
  },
];

/**
 * Создать полноценного бойца Combatant на основе выбранного пресета
 */

export const DEFAULT_PRESETS: CharacterPreset[] = [
  ...CAMPAIGN_HEROES_PRESETS,
  ...getAllSRDMonsters(),
];

export function createCombatantFromPreset(
  preset: CharacterPreset,
  pos: { x: number; y: number },
  nameOverride?: string
): Combatant {
  const id = `c-${preset.id}-${Date.now()}-${Math.floor(Math.random() * 1000)}`;

  return {
    id,
    name: nameOverride || preset.name,
    type: preset.type,
    color: preset.color || (preset.type === "player" ? "#3b82f6" : "#ef4444"),
    x: pos.x,
    y: pos.y,
    facing: preset.type === "player" ? "E" : "W",
    hpCurrent: preset.hpMax,
    hpMax: preset.hpMax,
    hpTemp: 0,
    ac: preset.ac,
    speed: preset.speed,
    initiative: 0,
    initiativeTiebreak: 0,
    dexMod: preset.dexMod ?? (preset.abilityMods?.DEX ?? 0),
    conditions: [],
    isHidden: false,
    hasActed: false,
    className: preset.className,
    level: preset.level,
    size: preset.size || "medium",
    movementUsed: 0,
    actionUsed: false,
    bonusActionUsed: false,
    reactionUsed: false,
    attacksPerAction: preset.attacksPerAction || 1,
    attacksMadeThisAction: 0,
    extraActions: 0,
    hotbar: [],
    attacks: JSON.parse(JSON.stringify(preset.attacks || [])),
    spells: JSON.parse(JSON.stringify(preset.spells || { slots: {}, known: [] })),
    abilities: JSON.parse(JSON.stringify(preset.abilities || [])),
    concentration: null,
    wildShape: null,
    saves: preset.saves ? JSON.parse(JSON.stringify(preset.saves)) : undefined,
    abilityMods: preset.abilityMods ? JSON.parse(JSON.stringify(preset.abilityMods)) : undefined,
    profBonus: preset.profBonus || 2,
    isAIControlled: preset.type === "enemy",
  };
}

/**
 * Конвертировать существующего бойца Combatant в шаблон CharacterPreset
 */
export function createPresetFromCombatant(
  combatant: Combatant,
  customName?: string
): CharacterPreset {
  return {
    id: `preset-custom-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    name: customName || combatant.name,
    type: combatant.type,
    color: combatant.color,
    className: combatant.className || "Персонаж",
    level: combatant.level || 1,
    size: combatant.size || "medium",
    hpMax: combatant.hpMax,
    ac: combatant.ac,
    speed: combatant.speed,
    dexMod: combatant.dexMod,
    initiativeMod: combatant.dexMod,
    attacksPerAction: combatant.attacksPerAction || 1,
    attacks: JSON.parse(JSON.stringify(combatant.attacks || [])),
    spells: JSON.parse(JSON.stringify(combatant.spells || { slots: {}, known: [] })),
    abilities: JSON.parse(JSON.stringify(combatant.abilities || [])),
    saves: combatant.saves ? JSON.parse(JSON.stringify(combatant.saves)) : undefined,
    abilityMods: combatant.abilityMods ? JSON.parse(JSON.stringify(combatant.abilityMods)) : undefined,
    profBonus: combatant.profBonus || 2,
    description: `Сохраненный боец: ${combatant.name} (${combatant.className || "без класса"} ${combatant.level || 1} ур.)`,
    isTemplate: false,
    category: combatant.type === "player" ? "heroes" : combatant.type === "enemy" ? "monsters" : "npc",
    tags: [combatant.className?.toLowerCase() || "боец", combatant.type, "пользовательский"],
  };
}
